---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app vikunja
  namespace: collaboration
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: vikunja/api
              tag: 0.22.1@sha256:c9415431e6235229302bb8f9ee6660b74c24859d1e8adbc4a3e25bd418604b57
            env:
              - name: VIKUNJA_SERVICE_TIMEZONE
                value: "${TIMEZONE}"
              - name: VIKUNJA_SERVICE_JWTSECRET
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: VIKUNJA_SERVICE_JWTSECRET
              - name: VIKUNJA_DATABASE_TYPE
                value: "postgres"
              - name: VIKUNJA_SERVICE_FRONTENDURL
                value: "https://tasks.${SECRET_DOMAIN}"
              - name: VIKUNJA_DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: pg-cluster-vikunja-pguser-vikunja
                    key: host
              - name: VIKUNJA_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: pg-cluster-vikunja-pguser-vikunja
                    key: user
              - name: VIKUNJA_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pg-cluster-vikunja-pguser-vikunja
                    key: password
              - name: VIKUNJA_DATABASE_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: pg-cluster-vikunja-pguser-vikunja
                    key: dbname
            volumeMounts:
              - name: files
                globalMounts:
                  - path: /app/vikunja/files
              - name: config
                globalMounts:
                  - path: /app/vikunja/config.yaml
                    subPath: config.yaml
                    readOnly: true
            resources:
              requests:
                cpu: 10m
                memory: 183M
              limits:
                memory: 1269M
          frontend:
            image:
              repository: vikunja/frontend
              tag: 0.22.1@sha256:f0223d441997fe29c377d0b476dc4bb2fc091b44b9c24d76b1b88c213df520c5
            env:
              - name: VIKUNJA_ALLOW_ICON_CHANGES
                value: "false"
            resources:
              requests:
                cpu: 11m
                memory: 35M
              limits:
                memory: 35M
          proxy:
            image:
              repository: caddy
              tag: 2.7.6-alpine@sha256:95ce04978787e23e35143d23b8af2fbb6d6de55213b54a2e9ed2dbf8ffe7313c
            resources:
              requests:
                cpu: 10m
                memory: 35M
              limits:
                memory: 240M
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: "external"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Vikunja"
          gethomepage.dev/group: "Collaboration"
          gethomepage.dev/icon: "https://vikunja.io/docs/favicon.ico"
          gethomepage.dev/description: "The open-source, self-hostable to-do app."
        hosts:
          - host: &host "tasks.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: tasks-tls
    persistence:
      files:
        existingClaim: vikunja-config-v1
        globalMounts:
          - path: /app/vikunja/files
      vikunja-config:
        type: configMap
        name: *app
        globalMounts:
          - path: /etc/vikunja/config.yaml
            subPath: config.yaml
      caddy-config:
        type: configMap
        name: *app
        globalMounts:
          - path: /etc/caddy/Caddyfile
            subPath: Caddyfile
    podAnnotations:
      configmap.reloader.stakater.com/reload: vikunja-configmap
      secret.reloader.stakater.com/reload: *app
