---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collaboration
resources:
  - ./helmrelease.yaml
  - ./config-pvc.yaml
  - ./configmap.yaml
  - ./secret.sops.yaml
  - ./volsync.yaml
