apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:M78mk9qzPF72+xbiqqan4syb,iv:Cc4kxt1IJQQGwf7VyChmgwMT/zoRoEfzDGGoU542qFc=,tag:BmZwu/G/qPWUm17uj1xMqg==,type:str]
    SECRET_ROUTE53_EMAIL: ENC[AES256_GCM,data:BPH42cfb6oFF3hFEfQn3uSjIZOBUTpYSOVLAxVbOx5nbagswYeDMWKJ4/gXUQeQ=,iv:nIMJlQOaZXZwfqdLnGpHdGR/eNFdXHf3rgNeeMLphGU=,tag:l6x211Y/0/m4p8xlMYDHbQ==,type:str]
    SECRET_ROUTE53_ACCESS_KEY: ENC[AES256_GCM,data:MLt00VS6nbWAUrVy/IrFVFwKc4E=,iv:MbQnR5guBIKuJAAU/ZhOuS9nnFU0YZvSKFOVliShEPw=,tag:zH4FtSjiOcYyZf513YxCEw==,type:str]
    #ENC[AES256_GCM,data:G+e2PdFO7001,iv:fV77Ds742d90KXPMcNNimq0NPIjT5Pa0RryRPt9emOA=,tag:pN8sImqmw5XFIxY3DJFTGw==,type:comment]
    SECRET_PGO_ACCESS_KEY_ID: ENC[AES256_GCM,data:WwSmPaz/VeXlYr2E4xkJFQ==,iv:ZFfvnxYg+9h38CZp5/6syctJMhgo5aLv4Bt475P2Jng=,tag:rYhraxheMZv/g/plP3UlfQ==,type:str]
    SECRET_PGO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZlZhUJLv0f/E5XmkKZ7TLQ==,iv:J4wErhToeavRwDmbGTnFchhjjZsQE9/x6oefT+YmM4o=,tag:742IHsQyVsaCBWA/20Rivg==,type:str]
    #ENC[AES256_GCM,data:cW4r9wNB8ArdCsU=,iv:BHYl1WVRtdFK8NEdY+PyqS44FQqq+q8g51cDxPFY1A4=,tag:Ki12R9fVL+9HmHWKQFVlBQ==,type:comment]
    SECRET_ALERT_EMAIL: ENC[AES256_GCM,data:oBTM6Wbixpw+3Rrfb7a+AqZAr3al,iv:761NyhMMaV26Eo/BoXLxlFNVfUU6h/62vJQoVobicks=,tag:TUP81dx298SpZSMpEtpf5Q==,type:str]
    SECRET_ALERT_SMARTHOST: ENC[AES256_GCM,data:P0Z0TWVX0MK0VfGXkR6LRhA=,iv:jb0DyXJzZdD3sDdJOF+c2PkveIrVfjxQwyw033ZaojI=,tag:wnMLawd/ahRv5UJKeAHVcw==,type:str]
    #ENC[AES256_GCM,data:71it4gU2qLQ=,iv:tKKlkxtu4yUvCiuOquhBI4IET7mhpQTjW7yaR7brAUU=,tag:Pt12VTSk0FhnMiRRWmaaKA==,type:comment]
    SECRET_VOLSYNC_RESTIC_REPOSITORY: ENC[AES256_GCM,data:IhmvIj8vYLNQ+ODZNCtZjwhnxWuHl/q6npGIlasCKJSwLCXYbKw=,iv:p3dkn9luaAa5rwo5FxS/+V22R4pstOUcWt+2Ibtg29Y=,tag:iSioQ6ZrSMgpoHYjEKpOzQ==,type:str]
    SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:YqBMSxCA5JG0F/Fdwn32Yw==,iv:9nIFwiA8PXnrb9KXwSE7Nlx/tqMzSglE9CwqmwO31gc=,tag:p+Hmy1cCcHPF0cyG+6boeQ==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s7BVks2soXtFpaAC/ZsW1w==,iv:uoxcagUr1RphRebrEbpZPdYcWZCiFQGqzr8miae4z84=,tag:O7RhEyiPXBR6E8LhRpfwNQ==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kMCefpaeAbh88o5dFURH/g==,iv:klCUYx/nHPzkiy8MbkTCHI4a+2EUT5ddT90HRbuMZKk=,tag:/KJmq1ne7xwNIFG/XYyU6w==,type:str]
    #ENC[AES256_GCM,data:xZh47TGO,iv:jF0N0eSumM2RSpcTxIeRL1Y4UnWPUEqVFiSYJQ9/qqo=,tag:vmBpwPmNLUxU5KRyMGn5dQ==,type:comment]
    SECRET_SYNAPSE_DATABASE_PASSWORD: ENC[AES256_GCM,data:YUQphyI/ae3mLvlT3/1++w==,iv:vgClWr0myGAr4GEH4I5878ClzCug5DlExj4n2NuxBAM=,tag:cld61O2355o4GY5Q3QNdJA==,type:str]
    SECRET_MATRIX_REDIS_PASSWORD: ENC[AES256_GCM,data:pb7lQUQ3uoYkYDnh1yCQ9w==,iv:qSkUFzcmI9lf1/R0VMpfoinegy7GGSftO/7UtlA4EzI=,tag:dNfgwUNdcKLqCzsSTRg99A==,type:str]
    SECRET_MATRIX_REGISTRATION_TOKEN: ENC[AES256_GCM,data:HkUD36Svwwc7KrjDkBwDSA==,iv:Rolq/s+/xQTIkP66sTDZxPfeugoUKExkrQz1MztSie4=,tag:moUCKEyB5FMgs7TyeEzxjw==,type:str]
    #ENC[AES256_GCM,data:P12h//D7nr3UvNWjiy4=,iv:1TXQawQajpN6PpU2rql7B2Zy1wfJ3maApYEU60ju3k8=,tag:WG/2U6YK8FbnxCGADT37yw==,type:comment]
    SECRET_GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:ag3Ow9VjabncTAAzwT/tXg==,iv:VdYlSQoTp16uuM/wYgfda4iaun0aY30O3KhwjED8s8Y=,tag:AQzt3OHNAeCY1MHBxDzoOg==,type:str]
    SECRET_GITEA_DATABASE_PASSWORD: ENC[AES256_GCM,data:UwAu+6IUuHcHtAlstMZ38w==,iv:Myk4jxndT1LMJcZTS6RcN+o34jOhr1G55hpD/gwkSXE=,tag:CL2RtTJFdaZuPlvKJH+5KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13srthcdyr08hp7w5xvezn5fex4p5kw7tky2pnrfef2u4j3uqsqgqwak9gc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArem1oZWdSMHMxUUN0enlY
            Rjg1MHNvVnk3TVNRRzFxRm54SDRSQWg0SEY0ClpBaXNmcGVnaHNzOUVoZjhqVkdH
            eVU2NnJQVmQ3UlBOSXpRK1d5dUF2UkUKLS0tIEpiMEVkbTlLNDVOSHlMZDdmWWFz
            V282dDRzaWRWTTNsSmxPS1VMSVR3MWcK51SIzHYF0CeGKi78nntDMicfqex89PoY
            HHdSiPuQP54GU4BRGpIzcQZFrQTKhkwsS6EOvOj4x2+eZQNPq6OaYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-02T03:38:48Z"
    mac: ENC[AES256_GCM,data:2L7DIvhQf2GVGcVYg9y7UVfs+IQI2MdAvNajVdB6L8fhTpDjCn2OlJi3WTVCfzBg518MXpVN3+29DrAQmP9N+4tsWHj7OTreacad62zMVirNijpqom7YLvFIGDgqCqvpVUnd2mzADLAlfWkkybbz5EFEVdl32IsVcyOLNC31NDs=,iv:gEePygx2ECaMKrcUA2fOx+kuDTcHVedRIPGBXa6IGTg=,tag:ONma7rdf9y3WC/ikuUIa3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
