---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minecraft-ftb
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-postgres-app
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/gameserver/minecraft/ftb
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minecraft-ftb
      namespace: gameserver
  interval: 30m
  retryInterval: 1m
  timeout: 3m
