---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-ftb
  namespace: gameserver
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    livenessProbe:
      command:
        - mc-monitor
        - status
        - --host
        - localhost
      initialDelaySeconds: 60
      periodSeconds: 10
    readinessProbe:
      command:
        - mc-monitor
        - status
        - --host
        - localhost
      initialDelaySeconds: 60
      periodSeconds: 10
    image:
      repository: itzg/minecraft-server
      tag: java8-multiarch@sha256:9386d1ce794df35db59d91c2fe40a07b2f22963e11f29ec951955087fa3b73cc
    minecraftServer:
      eula: "TRUE"
      version: "1.12.2"
      type: "FTBA"
      ftbModpackId: "35"
      ftbModpackVersionId: "3.6.0"
      difficulty: hard
      pvp: true
      memory: 6144M
      serviceType: LoadBalancer
      motd: "FTB:R"
      loadBalancerIP: "${LB_MINECRAFT_IP}"
      externalTrafficPolicy: Local
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-ftb-data-v1
    resources:
      requests:
        cpu: 34m
        memory: 4506M
      limits:
        memory: 5279M
