---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./crunchydata.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jameswynn.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./minecraft-server-charts.yaml
  - ./nextcloud.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./traefik.yaml
  - ./weave-gitops.yaml
