---
apiVersion: v1
kind: Namespace
metadata:
  name: comms
  annotations:
    volsync.backube/privileged-movers: "true"
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    kustomize.toolkit.fluxcd.io/prune: disabled
